### ISSUE TITLE
Sector and location percentages MUST add up to 100%

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#234]
Hi Rashid - I realise that I had not been fully clear before - I had stated that percentages needed to be limited to 100%, but now realise that they must = 100% otherwise we are going to have real problems with the calculations in the reports.

I can think of two ways of doing this - firstly:
Check before the user can leave the page...(check on 'next')
OR,
Automatically have an entry called 'not available' which automatically adjusts to fill the gap to 100% 

Let me know what you think?

**Comment by raashidahmad** [comment]
@matmaxgeds I think we will have use mix of the suggestions given above because:

1) What if the user closes the browser or click on another tab. This will allow the user to leave it through other ways.
2) If we put a record automatically of not available percentage, it is a good idea, but it has some cons, which are every time you make an entry, delete an entry, or update percentage for other sectors, you will have to adjust available percentage every time.

By looking at the suggestions what i am thinking is what if it works this way:
When requesting reports, if sectors for any projects are missing percentages, we put the not available percentage there.

This approach has one issue, that is, your APIs will make processing for such condition on every request. Let me know about your opinion.

**Comment by matmaxgeds** [comment]
thanks for these thoughts @raashidahmad - I am happy to go with the way that you are suggesting where we ignore it on the sector/location input, but process it during the reports - I think we can cope with a slowdown there as users will expect it a bit.

Or if you decide that option 2 is easier - I don't think the user will need to do this, we could do it for the, i.e. it you have one sector for 50%, the table shows another for 'not available' at 50%, then if you add another sector for 20%, when you submit, the check that it is not >100% only looks at the user added sectors, and finds 70%, and so adjusts the AIMS adjusted 'not available' sector to fill the remaining 30%, so there should not be extra user clicks and maybe it can be integrated into the current check for >100% method.

**Comment by raashidahmad** [comment]
It is implemented with option 2 and works the way as below:
1. If sectors are added, and left percentage will be assigned to a sector named not available
2. To edit any percentages, user may delete not available, and may save the percentages, if required, the remaining percentage from the 100% will be assigned to Not Available.
3. It similarly works for locations, with only one difference, that is any left percentages are assigned to location named as Unattributed.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks, this sounds a good fix for a complex problem
