### ISSUE TITLE
Encode report options into the report URL

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#28]
The ToR describes how the URL for a report needs to allow a user to return to the same report (but with updated data) at any time in the future. So at the moment, all reports use the URL: http://104.140.103.166:7001/project-report

ideally this would be http://104.140.103.166:7001/sector-report?years=20172018&sectors=Security&mode=webpage - like you would expect an API..........and for the pdf "mode=pdf" and then mode=excel etc........to adjust what would be returned. If there is no mode, then it is to the website version?

This url then needs printing on the print version of the report - as the current link is now. If it could be made a hyperlink from the PDF then even better

**Comment by raashidahmad** [comment]
@matmaxgeds As you know that there are many options for search, such as multiple sectors, organizations, locations. This is normally array data, there are complexities involved with such data sending through Url. That's why all the data is posted through post request, which means as a part of the body of the request. As far as, Excel, and PDF formats are concerned, i will work on this aspect of the reports.

**Comment by matmaxgeds** [comment]
Hi - let's discuss this in MIA in March - it is quite an important feature (and one that is in the technical specifications) that people should be able to access an updated version of the same report by clicking a link in a report or in an email so we need to think how to make this achievable. Perhaps a compromise is that we can have shortlinks which encode the post data which are generated with each report.
