### ISSUE TITLE
data entry: when entering the start/end FYs for a project, use dates

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#382]
We cannot expect that when entering data, the user is aware of the Somali FYs so they should enter dates, and these should be converted to FYs for them when the project is being saved. Like when we informed the user about the exchange rates, we can also inform them of the FY that their date has been mapped to.

This means that for the data entry, we need a datepicker.

**Comment by raashidahmad** [comment]
Fixed. In order to allow user with entering dates instead of years. I had to store dates, because if a project is loaded for edit, we won't have any way to track what date user entered while creating the project. 

There are few things i would like to mention about this feature:

1. You will see date format will be switching on focus and loose focus. This is because we do not have labels for text fields in this case, because we are adjusting many fields on the form.

2. So in order to cope with the situation we keep changing field type, so that when there is no date selected, it must show Start or End date.

Please add test projects for now, i may delete it, just keep a track of test with some keywords.

**Comment by raashidahmad** [comment]
With this feature, i felt we will have to do the import again, because we have picked up years from the projects. Data import issue is open, will do it with that.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks for this, really looks good now.

Understood on the re-import, I think there are going to be a bunch of things about the import that need tweaking so let's try and solve several in one go before re-doing the import maybe, unless the actual import is quick now the script is written?
