### ISSUE TITLE
Excel export - numbers entered as text

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#491]
Hi Rashid, in the excel export, all the numbers have an " ' " in front of them, so you cannot do formula's with them etc, please write them out as numbers instead, and right justify all numbers, and left justify all text.

**Comment by raashidahmad** [comment]
Hi Matt, during a test i found that in order to allow numeric calculations using some built-in functions such as SUM, we need to remove commas, and then it worked fine. Can you please test and confirm as i am not an expert of Excel and do not know if calculation functions are applicable on numbers with commas.

**Comment by matmaxgeds** [comment]
@raashidahmad agreed, if you remove the apostrophe's then things like sum() work, but we cannot expect the users to know how to do that, or to do that for all cells

**Comment by raashidahmad** [comment]
@matmaxgeds I am confused about this, i do not see any apostrophe's in the numeric values, but instead comma separated numeric values. Please see the attached excel sheet which i generated a while ago using AIMS.

[AIMSProjects-637182181387038056.xlsx](https://github.com/somaliaims/Somali-AIMSUI/files/4249608/AIMSProjects-637182181387038056.xlsx)

**Comment by matmaxgeds** [comment]
@raashidahmad see screenshot, when I open the file in Excel, then it is all 'number formatted as text or preceded by an apostrophe - which makes the sums not work

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for the confirmation. In order to test it with other spreadsheet software i uploaded it Google drive and tested with Google sheets. This seems to work fine with Google sheets. Please see it here:
https://drive.google.com/file/d/1e1MeHVPtiyFoofkRDwN4mY_wJtRfSbx0/view?usp=sharing
The issue you reported suggests me that we should not format the values with commas in order to avoid this issue. Please share your opinion.

**Comment by matmaxgeds** [comment]
@raashidahmad - yes, google sheets appears to strip the apostrophe's. If you open it is Excel, the apostrophe's that are before each number are the  issue, not the comma's.

**Comment by matmaxgeds** [comment]
![Uploading Screenshot from 2020-02-25.png…]()

**Comment by raashidahmad** [comment]
@matmaxgeds I have changed the formula, i am not putting any apostrophe's in numbers, instead i believe the format we generated in not interpreted with the Software you are using. The numbers are showing perfect using these software:
1. https://www.wps.com/ (It is installed locally on my computer and working perfectly)
2. Google sheets

I am keeping it open until we reach a solution.

**Comment by raashidahmad** [comment]
@matmaxgeds Please also give it a consideration while you are testing the new build.

**Comment by matmaxgeds** [comment]
closing here as replicated in #504
