### ISSUE TITLE
data entry - IATI entry is confused

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#493]
When I click on the source data entry icon next to the start date....I get the start data source data fine, but then it comes with the description, where it should be the end date instead? This problem is repeated for a lot of the new source entry things.

Secondly - if I go to manual entry, then change my mind and leave it blank, I cannot use the source data entry any more, unless I set a date, and then overwrite it, please can we allow overwriting of blank dates?

Finally, there is not need for "currency: USD" to show when all we care about is the source project name and the dates

![Screenshot from 2020-02-24 21-51-45](https://user-images.githubusercontent.com/432153/75190382-7929bc80-5750-11ea-805a-15bd946e8e9d.png)

**Comment by raashidahmad** [comment]
@matmaxgeds the following changes are made in response to your suggestions with an exception of blank date:
Problem: The problem with date text field is that, date field does not allow entering manual dates. In order to accomplish it editable, i convert the date text field to normal text field, when editing is done, on loosing focus, it is converted back to date. The reason it leaves the date field blank is because of allowing the user to edit it manually. So we are in limitation of control for this.

For other things suggested, they are implemented as below:
1. When title selected, title and description can be selected and editable.
2. When start date is selected, start and end date is shown and vice versa.
3. For project value, financials such as budgets and transactions are shown and select-able.
