### ISSUE TITLE
data entry - project currency list small

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#497]
Hi Rashid - please can we allow all available currencies in the list to pick from? How come just these ones were made available?

**Comment by raashidahmad** [comment]
@matmaxgeds we decided at some stage after changing the logic for exchange rates that only those currencies will be shown in the dropdown, which has exchange rate set for the current year, this is in manager user control to set the exchange rates for the currency.

**Comment by matmaxgeds** [comment]
@raashidahmad ok, this was a confusion, the aim was to split the dropdown into two parts, with all the 'in-use' currencies at the top, and then all the rest of the available currencies. Otherwise there is no way for a user to ever use a new currency.

**Comment by raashidahmad** [comment]
@matmaxgeds, this is a good idea, however, it will be difficult to tackle and will create more situations to handle. To make it easy to implement, i am now showing all the currencies, if a manual exchange rate is available, it will use the manual average rate, otherwise will use the rate from source.
