### ISSUE TITLE
Change organisation

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#538]
As well as change password and delete account, we need to offer 'change organisation'. I am hoping that this is not a new procedure - see below:

- [ ] Add 'Change organisation' option to 'Account management' page
- [ ] Provide a dropdown to select the new organisation
- [ ] This triggers the same procedure as a new user joining e.g. an email to the existing users from that organisation, or to management users to approve the new user. Once approved, the organisation changes. If not approved, nothing happens
- [ ] ?? allow users to submit multiple change organisation requests? Might be easier than dealing with a process to queue them etc - just process them in the order they get approved, whatever that is

**Comment by raashidahmad** [comment]
@matmaxgeds 
1. In order to accomplish this task, we will need a table on the backend, that will store the user requests for change an organization.
2. Without this we will not be able to track the request. We also need to define will the user be able to login with the previous organization.
3. We also need to write the notification API for this to be shown into the notifications list
4. We will write the APIs for approval or rejection of the request, corresponding email actions.

I would mark it a task for phase 2 or suggest me please what is on your mind?

**Comment by matmaxgeds** [comment]
Closing as we are preferring that users delete their accounts and apply again to change organisation
