### ISSUE TITLE
First user email needs to not be hardocded

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#567]
Matt: Because someone else deploying might want to use a different initial email/password, it would be great if we could pass those details via the command to spin up the server rather than encode them somewhere in the image
Rashid: For a custom email, I am thinking about that, we can even put it in the configuration file but the problem is that while running a docker image you cannot access the configuration file. I will do some tests if I can inject that information at the command line.
Rashid: About login issue, I am now thinking to allow the user to provide an email address while running the image. I am doing some research on it. In the meantime, a quick question about this is that, what should be the organization of this user created through command line?
Rashid:     I am doing some research about a good way to get email from the command line and insert it to the database for the first Manager account, however I have few questions about it.
        What will be organization for the user?
        Similarly, the organization type.
Matt: For the first user, that is difficult as we don't know even what organisations they will enter, or what organisation types.......we can think about it slowly as it is not priority right now. I guess we would have to pass all 4 parts: email, password, org, org_type....and also setup that org and org type in the relevant tables as well.

**Comment by raashidahmad** [comment]
@matmaxgeds as we are heading to end the phase 1 things. Your suggestions are required here, please keep few points on your mind while suggesting:
1. It is difficult for user to provide a long list of attributes through command line, and may mix the sequence of attributes provided.
2. The easy way I am thinking about is to create a default user and allow the user to update account Information.

**Comment by matmaxgeds** [comment]
Hi @raashidahmad - agreed, the command line is not a solution, however this must be a common issue with deploying docker containers - I believe this is why they have docker compose files - there is an example here for wordpress but I think it shows passing the kind of things that we are currently doing via the command line, see https://docs.docker.com/compose/wordpress/ - then the user can edit that file, and just run 'docker-compose up' - I believe you could put all three containers in the same docker_compose.yaml which would make deployment even easier.

**Comment by raashidahmad** [comment]
Hi @matmaxgeds, thanks for sharing helpful resources. Let me explain all the parts to get a clear picture of it:

1. The solution you are proposing is for programmers. In order to run docker compose, you need the source code on your local system. Otherwise, docker compose or docker build will not run. If someone can manage the source code on the local system, we have bunch of options then, the first option is the very easy to use json configuration file, where you can put up all this information, or we can have a text file where we can put all this information. Then can run docker build or docker compose whatever the situation is. I believe this is not going to be a user friendly solution, if the user first clone the source code, and then run docker commands. For programmers, this approach is easy and perfect as it is fully customizable. 

2. The second point is that I have kept the Images Independent. There are bunch of reasons for it. 

- a) We want our Image Independent of SQL Server or any version of It.
- b) It will give the end user choice to keep the SQL Server within the docker container or out of the docker container specially for production I would recommend, where user would have full control. You can configure SQL Server Information just at running the APIs docker container.
- c) Third point is that we cannot keep the UI and API both in a same container, both the containers will run on a different ports with their own Interfaces to Interact with.

3. To tackle the first user situation the options we have are:

- a) Either go for the command line parameters originally proposed. Please also suggest me how to Input organization type (What should be the default type), organization name etc.
- b) Initialize the default user Information in the database with a default organization type (Later name can be changed), default organization name (Later can be changed), default email (Which will be updated after the user Input through command line), default password (Later can be changed). So the advantage of this approach would be user will only provide SQL Server Information and Email Id only. 

If there is anything confusing with this discussion, please propose me a time to have a call on this Issue.

**Comment by matmaxgeds** [comment]
@raashidahmad I was trying to read some more and it looked to me that docker-compose just pulls the images i.e. does not need the source code e.g. see the examples here: https://gabrieltanner.org/blog/docker-compose or am I still not understanding correctly?

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for looking into the technical stuff to assist me. Let me explain it:
1. We can build images using docker or docker-compose.
2. We build custom images (for example for AIMS), that is based on other Images for example, in our case we need .NET Core base image to build the Image for AIMS.
3. docker-compose gives us a benefit where we can combine sequence of building multiple Images into a single Image and set some configurations.
4. docker-compose will use the Image that we will build using a dockerfile in our case.
5. When I will run docker-compose or docker build, it will create the Image that the end user will use. End user will not see any files but will use only commands. In fact docker-compose or docker build is for technical people.
6. If an end user can download the Image and can then use the docker-compose his/her self, then sure we have a solution, but It would be more technical stuff. Sometimes, there are more technical messages an end users see, I can rank it a possible solution If you agree that is manageable for an end user. (Note: I have used docker compose with build and package both, not for this situation, so I will give it a try first)

Please see one more solution if this seems reasonable to you:
While thinking over it simplify it more I was thinking to create a default user with default organization name and email. On the very first login to the very first user, we can allow management user to change the organization name and email. But this screen and action will be allowed just once for the very first management user. So, we have all these options. Please let me know anytime if you want to speak on this and want more explanation through a Skype call.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks, this really helped - I agree that the next stage is a skype call - are you free tomorrow - if so please pick what time is best for you, then we can decide if there is anything to do here in Phase 1 or if it is all in phase 2.

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks. Sure, I can manage almost anytime tomorrow which works for you. Please suggest me some time here or on Skype.

**Comment by matmaxgeds** [comment]
@raashidahmad - for the purposes of completing phase 1, let's assume that the initial user email, org name, org type etc are all passed via the command line.

This is because when I wrote out the alternative (see below), it is a mess in post install
1. Encode an initial user, org, org type, into the command line, so that the first manager can use to login, and then delete once they are registered
2. this needs to be tested from scratch to check out the permissions on deleting a manager as the only other user
3. please update the deployment instructions to have a 'post install' section that includes the instruction on how to login as the default user, add the email sending details, logout, register the new management user, approve as default user, upgrade to manager, receive the email as the new user, logout as default, login with new user, downgrade the default user, delete the default user, delete the default user default organisation and default organisation type.

**Comment by matmaxgeds** [comment]
@raashidahmad noting here that we agreed on skype to go for the default user and long post install readme additions approach for Phase 1

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks as agreed, I have uploaded and shared all the helping stuff required for deployment here: https://github.com/somaliaims/Somali-AIMSUI/issues/422 
Closing this issue, we may create issues for phase 2, if required.
