### ISSUE TITLE
IATI data import of organisations

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#572]
There are no IATI import buttons next to the funder/implementer data entry fields

**Comment by raashidahmad** [comment]
@matmaxgeds there are a couple of things related to this issue:
1. This source buttons become available when you save a project. The reason being for this is that:

1.1 The organizations from IATI are not in the list of organizations as we are now storing IATI organizations in a different table. So if mix these organizations with AIMS, it will create a mess, as these organizations does not have a valid Id in the database and have a null Id in this case. Having Id means that an organization is saved in the database against an organization.

1.2 While i studied the API and found that any IATI organization if selected to be an AIMS organization, it is saving against a default organization type, for example "Default organization".

1.3 This is because we changed the idea later and decided to save IATI organizations into a separate table.

1.4 This issue seems to be complex, and we need to address it in a simple way, in terms of logic and UI both.

**Comment by matmaxgeds** [comment]
Thanks for these thoughtful comments @raashidahmad - I will think harder/again and get back to you as there are a lot of things that I had not thought about

**Comment by matmaxgeds** [comment]
@raashidahmad I got the chance to think about this some more. The bits about having IATI orgs in a separate table are very correct. We do need to correct the 

1. There are already IATI/AIMS source buttons for the name, description etc, so we should be able to get them for the organisation
2. Can we import organisations from IATI when doing data entry in the same way as we do when registering new users e.g. when they select that the one they want is not in the list, they create one, including providing the organisation type, just this time the name would be pre-filled from IATI (although they can edit it)? Would the be a popup or something?

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for the suggestion.
1. It is possible and Implementable. I am labeling it Phase 2 for the moment.

**Comment by matmaxgeds** [comment]
@raashidahmad this was closed because it was completed?

**Comment by raashidahmad** [comment]
@matmaxgeds We changed our plan working with organizations, now we have a separate table for organizations and IATI organizations, so we do not mix IATI organizations with data entry, but only uses it to filter IATI projects. Please close it if you agree or let me understand your thoughts otherwise.

**Comment by matmaxgeds** [comment]
Thanks - I just saw the IATI org filter is implemented on the data entry page - that is what I was checking for, closing
