### ISSUE TITLE
Join a project seems strange

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#573]
See screenshot - I am logged in as UNDP, just one project is asking me if I want to join it, but lots that UNDP is not a member of are not asking me - what is happening in the logic here?

![Screenshot from 2020-05-31 17-16-00](https://user-images.githubusercontent.com/432153/83355899-93cc8c80-a362-11ea-833e-24eb68a1dd57.png)

This project is not offering me to join, but I am not a member already, now come? Why is just one project asking me to join?
![Screenshot from 2020-05-31 17-21-48](https://user-images.githubusercontent.com/432153/83355985-3a189200-a363-11ea-8978-47cadd06d784.png)

Why just this one?
![Screenshot from 2020-05-31 17-23-07](https://user-images.githubusercontent.com/432153/83356008-6cc28a80-a363-11ea-9040-dafa9bd7e23d.png)

**Comment by raashidahmad** [comment]
@matmaxgeds Ownership for a project works this way:

1. If a user (organization) created the project.
2. If a user (organization) is a funder 
3. If a user is Implementer

Note:- Since we imported projects using no actual users. So by default, aims.developer18@gmail.com is the owner. From the recent query i ran on the server, aims.developer is direct owner of about 447 projects other than being a funder or implementer.

In order to get a better idea, please login with your own account (For example work@matt...) as UNDP. For reference i am attaching a snapshot i just checked with my account. Please close the issue if you find it work as expected.

![ProjectOwnership](https://user-images.githubusercontent.com/2605356/83358508-7a8d0580-a38d-11ea-8066-3101803b7802.png)

**Comment by matmaxgeds** [comment]
ok, thanks - I had not realised that I was logged in as aims.developer18. So this is only a problem for that user, and therefore will not ever occur again.
