### ISSUE TITLE
Email users option - formatting vs export

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#581]
1. Please read all before implementing
2. We could add some WYSIWYG formatting options (bold, underline, italic, bullets, links, paragraph break) for the email sendout feature.
3. Alternatively, I think it might be easier to offer the facility to export a contact list....that way the user can copy them into their own email (use their normal formatting, use attachments etc).....and also get all the replies.
4. If not their own email, we would need a feature to add the email to put as the 'to' field with all the rest in CC - otherwise all the replies will get lost.

**Comment by raashidahmad** [comment]
@matmaxgeds As I am approximating efforts, so trying to get the exact Idea about the features for Phase 2. As far as I have understood the features, are given below:

Point 3: This means we will export the contacts list as a string of emails, separated by commas, so that the user can copy and paste it to send emails.

Point 4:- I am not very clear, what the system will do in this part of the feature?

**Comment by matmaxgeds** [comment]
@raashidahmad 

1. no need
2. not needed
3. We are replacing the entire 'email users' option (and page/form) with the ability (via a button) to download a comma separated text (txt extension) file of users emails, and a separate one for management users
4. No longer needed
5. This button can be on the 'users' page, and the 'management' users page, meaning we can remove the specific management page for 'email users'
