### ISSUE TITLE
"date of last update" column on organisation page

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#603]
It would be useful for management users order the organisations page by the date of their last update (not login), this means adding a new column to the table, and making it sortable

**Comment by raashidahmad** [comment]
This is implemented. @matmaxgeds since this is a new column added, so avoid the nulls and keep a default update date for the organizations it has been kept as 20th March, 2020. Which I have assumed the launch date for the AIMS. Afterwards, if a new organization is added or updated, its last date will be updated in the database.
