### ISSUE TITLE
Tackling exchange rates in different sections

### ISSUE THREAD

**Issue by raashidahmad** [somaliaims/Somali-AIMSUI#609]
There are two ways exchange rates are currently tackled using AIMS.
1. Getting exchange rates using openexchange APIs whenever new project is created (Project start date is used), or updated, or any disbursements (Disbursements date is used) are added.
2. Manual entered rates for an year. These rates are used to convert the values between National and Default currencies on the report.

Note:- We have changed the logic for exchange rates many times. Manual exchange rates were added at a very later stage just before the launch of AIMS. We are also building exchange rates archive, currently we have exchange rates archive for 162 dates in the database.

We need to define some rules to Implement how the exchange rates should be used. 
1. If we want to use one exchange rate for the whole year, how it will be calculated for a project? Using the project start date or end date?
2. We also have disbursements for different financial years. Do we need to use the exchange rates for the year disbursements are made against. If so, then it may be different from the project value.
3. There are also chances that the user has not entered the manual exchange rates for an year which is used for project start/end date or disbursements financial year.

Currently, we are mostly relying on open exchange rates, and using it against the dates. For example, for a project value, start date is considered, for project disbursements, same exchange rate is used, which is used for the project.

**Comment by matmaxgeds** [comment]
@raashidahmad thanks for this:

1. We have setup multiple sources of exchange rate, so that if one source does not have the needed rate, the other might
2. We currently have two sources, and the AIMS allows management users to decide which one we use if both sources have the needed exchange rate - please confirm this
3. We also have a logic for what to do in terms of going backwards to the most recent exchange rate, when we do not have a rate for the needed date

Now onto your questions - which are good ones
1. Lets use the project start date as when the project is entered, the end date will almost always be several years into the future, so the start date will be closest to an exchange rate that we have
2. This is a good point, and it would be nice to do a complicated solution with different exchange rates for different years, but so that we do not have trouble later, we can use the exchange rate that is in use for the whole project (based on the start date) for all the disbursements as well - I think this is what you are already doing, but good that we both know it now
3. Yes, in that case we will use a) openexchange rates for the right date/year, and if that does not have it, go backwards in time until we find a source that does, does that make sense? The logic for finding an exchange rate should be in the exchange rates API, so all exchange rate calls use the same logic and we only have to write it once.

**Comment by raashidahmad** [comment]
@matmaxgeds We had Implemented settings for multitple resources for exchange rates, but later on decided to use average exchange rates. Please note some of the points of how exchange rates are Implemented.
1. To overcome many issues while entering project / importing project we use exchange rates from open exchange APIs since we were not sure will we get the average rate from the manually entered rates. So, we are not allowing the sources to be selected by the management user anymore. Please note we changed the logic for exchange rates many times.
2. We are using manual exchange rates only for national and default currency conversions.

The only decision we need to take in this ticket is to when to use manual and ex rates from openexchange, and what dates to consider while entering project basic data and disbursements. You have already replied me with the answer for the second part of this question, for example, to use starting date of the project to calculate the exchange rates.

**Comment by raashidahmad** [comment]
@matmaxgeds @mohamedgele22 
I have thought over using exchange rates feature in the system and have come up with the following thoughts.

Since we had decided to use average exchange rates that are entered manually for every year just once (The idea was proposed by Sarah). When entering the exchange rates manually, the rate is suggested by the openexchange with the facility that user can change it if wishes. 
Currently, they system is using average exchange rates to convert financial values only on reports at runtime. On the other hand for each financial entry against a project ex rates are calculated using the openexchange against the specific date. To bring the uniformity and standard for using exchange rates, I would suggest the following given below:

1. Use average exchange rates (one entry for a year) every where in the reports and data entry against each financial entry.
2. The archive for the exchange rates will keep building as before.
3. The only difference would be that average rate for a currency will keep changing with the every new entry in the archive against the particular year.
4. If a user has not entered a manual entry for the newly started year (or financial year), the AIMS will take care of it, and will keep maintaining the ex rate for they year user has not entered it yet.
5. If the user wants to change an average, the user must be able to change it. (We are calling this annual exchange rates as manual exchange rates)

Note:- I would welcome a talk on it if required. Please suggest me the day and time, and I will try to manage it.

**Comment by raashidahmad** [comment]
@matmaxgeds @mohamedgele22 Great if I can get feedback on it. I am planning it to be my next task.

**Comment by matmaxgeds** [comment]
@raashidahmad 

1. Yes, I think we should go with the simplification that everywhere in the AIMS (data entry, and also export e.g. reports) that we only use a single annual average exchange rate for each currency pair. This will be stored in a table of exchange rates.
2. Then the important questions is how we fill that table - we have two sources:

Source 1: Manually entered exchange rates from the central bank
Source 2: Openexchangerates
Logic for between the two sources: Calculate the annual average based on the manually entered exchange rates if they exist for the year needed, otherwise use the data from open exchange rates

Logic for the future: Same as for the past - calculate an average using the manually entered rates if they exist, and the openexchange rates if none exist for the year.

Script - update the calculated annual averages each month, checking to see if there is new information.
When a manual exchange rate is added, trigger the script to recalculate that average.

FYI - on the openexchange rates page, there is no need to show all the exchanges rates that it has found. Just confirm that it is working correctly with a green/red indicator - next to where the API key is entered.

We do need a page where you can lookup the exchange rate that the AIMS has calculated for a pair in a given year, not a table, just a dropdown for the first currency, the second (National currentc + default currency) and the year.

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for detailed note.

You explained it very well, and the idea you proposed seems to simplify it. However, with the current Implementation, it raised few questions in my mind.

Questions and comments:
1. We have currently the table structure that allows one entry per year for the manual exchange rates. Do we need to store the manual ex rates on a month basis? Which means an entry for each month, and then twelve entries a year for each currency? If this is the case, we will need some extra work.
2. You proposed that we should show the pair of ex rates that are used to calculate the average annual ex rate.  From this you mean to show the list of ex rates we have acquired from openexchange?
3. Currently, when a project is entered we take the start date of the project and try to get the ex rate from the annual ex rates table. If it is not there, we take it from open exchange rate, then check what other entries from openexchange we have in the database for that particular year, calculate the average and store it as the ex rate for that project. Please note, the average will keep updating with the new entries.

If the answer for the questions is simple, please propose me here in the comments 
or
I am open about the idea to speak on this issue in the upcoming meeting or any day that works for you.

**Comment by matmaxgeds** [comment]
1. For the manual rates, the user enters currency A, currency B, the date, and the rate - so it could be for any period, and any pair of currencies
2. No need to show the pair, just the resulting exchange rate for the pair of currencies and date that the user wants to lookup
3. Exactly, updating annual exchange rate during the year is fine

Thanks for the good questions

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for the answers.
The point that was confusing me was pair of currencies. Actually we are keeping the exchange rates against the default currency. Also, the openexchange only provides us exchange rates in USD as we are using the free version. But we are using formula to display the values with respect to default currency. Now understood the meaning of pairs, we are storing the ex rates as mentioned above. So the explanation above is now clear to me for the calculation of annual ex rates, will Implement it in the upcoming days.

**Comment by raashidahmad** [comment]
@matmaxgeds While writing the logic for the Implementation of the suggestions given above, I have come across a situation, which I have documented in a document to easily address the points. Please see the document using the link given below:

https://docs.google.com/document/d/1-GN1qQuEwV3dbVixYAyPsXtclCkYhEJOPfyRDhdH_Vw/edit?usp=sharing

I will pause work on it until we discuss it in the meeting or you suggest me after reading the document.

**Comment by matmaxgeds** [comment]
Hi @raashidahmad thanks for the good writeup - the automatic option 2 sounds best - sorry that it is more work

**Comment by raashidahmad** [comment]
@matmaxgeds Thanks for the review and suggestion. Noted.
