### ISSUE TITLE
Envelope reports - show the full range of years in the dropdown

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMSUI#627]
Double check what is limiting the years available for the envelope reports (in the start year and end year dropdowns), it should draw from the available data - check this is not hardcoded, or limited somehow.

Also check what happened to all the 2018 envelope data that we had on the initial entry? Was there any?

@mohamedgele22 you had some other issues with the envelope report?

**Comment by raashidahmad** [comment]
@matmaxgeds @mohamedgele22 The logic behind displaying only three years is the logic behind the concept of envelope. That is displaying only these years, (current - 1, current, current + 1). Please see some facts regarding the envelope report given below:

1. We cannot display more than 3-4 years on the report. The reason is that we cannot adjust too much data on the single page. Think about if we select a range of 10 years or so?

If you feel, that is understandable, please give me a clue, so that I move ahead with displaying all years.

**Comment by matmaxgeds** [comment]
@raashidahmad - in the locations report, we show about 12 columns, so I think it is fine to allow users to add a lot more columns to the envelope report if they want to view more of the history, it will be 7 years before there is enough data for more than 10 columns anyway.

So please enable selecting envelope data from all avilable years, not just the current 3 years (that 3 years part is just for the envelope data entry, and sorry for being unclear, it was not meant to apply to the report side)

**Comment by raashidahmad** [comment]
Updated as suggested.
